// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgeDispenses holds the string denoting the dispenses edge name in mutations.
	EdgeDispenses = "dispenses"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DispensesTable is the table the holds the dispenses relation/edge.
	DispensesTable = "dispenses"
	// DispensesInverseTable is the table name for the Dispense entity.
	// It exists in this package in order to avoid circular dependency with the "dispense" package.
	DispensesInverseTable = "dispenses"
	// DispensesColumn is the table column denoting the dispenses relation/edge.
	DispensesColumn = "user_dispenses"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
