// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Dispense is the predicate function for dispense builders.
type Dispense func(*sql.Selector)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
