// Code generated by entc, DO NOT EDIT.

package patient

import (
	"time"
)

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstname holds the string denoting the firstname field in the database.
	FieldFirstname = "firstname"
	// FieldLastname holds the string denoting the lastname field in the database.
	FieldLastname = "lastname"
	// FieldCardid holds the string denoting the cardid field in the database.
	FieldCardid = "cardid"
	// FieldAllergic holds the string denoting the allergic field in the database.
	FieldAllergic = "allergic"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldBrithday holds the string denoting the brithday field in the database.
	FieldBrithday = "brithday"

	// EdgeDispenses holds the string denoting the dispenses edge name in mutations.
	EdgeDispenses = "dispenses"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// DispensesTable is the table the holds the dispenses relation/edge.
	DispensesTable = "dispenses"
	// DispensesInverseTable is the table name for the Dispense entity.
	// It exists in this package in order to avoid circular dependency with the "dispense" package.
	DispensesInverseTable = "dispenses"
	// DispensesColumn is the table column denoting the dispenses relation/edge.
	DispensesColumn = "patient_dispenses"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldFirstname,
	FieldLastname,
	FieldCardid,
	FieldAllergic,
	FieldAge,
	FieldBrithday,
}

var (
	// FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	FirstnameValidator func(string) error
	// LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	LastnameValidator func(string) error
	// CardidValidator is a validator for the "cardid" field. It is called by the builders before save.
	CardidValidator func(string) error
	// AllergicValidator is a validator for the "allergic" field. It is called by the builders before save.
	AllergicValidator func(string) error
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// DefaultBrithday holds the default value on creation for the brithday field.
	DefaultBrithday func() time.Time
)
