// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/wipha26/app/ent/dispense"
	"github.com/wipha26/app/ent/drug"
	"github.com/wipha26/app/ent/patient"
	"github.com/wipha26/app/ent/user"
)

// Dispense is the model entity for the Dispense schema.
type Dispense struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DispenseQuery when eager-loading is set.
	Edges             DispenseEdges `json:"edges"`
	drug_dispenses    *int
	patient_dispenses *int
	user_dispenses    *int
}

// DispenseEdges holds the relations/edges for other nodes in the graph.
type DispenseEdges struct {
	// Drug holds the value of the drug edge.
	Drug *Drug
	// Patient holds the value of the patient edge.
	Patient *Patient
	// User holds the value of the user edge.
	User *User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DrugOrErr returns the Drug value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DispenseEdges) DrugOrErr() (*Drug, error) {
	if e.loadedTypes[0] {
		if e.Drug == nil {
			// The edge drug was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: drug.Label}
		}
		return e.Drug, nil
	}
	return nil, &NotLoadedError{edge: "drug"}
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DispenseEdges) PatientOrErr() (*Patient, error) {
	if e.loadedTypes[1] {
		if e.Patient == nil {
			// The edge patient was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: patient.Label}
		}
		return e.Patient, nil
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DispenseEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[2] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dispense) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // note
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Dispense) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // drug_dispenses
		&sql.NullInt64{}, // patient_dispenses
		&sql.NullInt64{}, // user_dispenses
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dispense fields.
func (d *Dispense) assignValues(values ...interface{}) error {
	if m, n := len(values), len(dispense.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field note", values[0])
	} else if value.Valid {
		d.Note = value.String
	}
	values = values[1:]
	if len(values) == len(dispense.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field drug_dispenses", value)
		} else if value.Valid {
			d.drug_dispenses = new(int)
			*d.drug_dispenses = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field patient_dispenses", value)
		} else if value.Valid {
			d.patient_dispenses = new(int)
			*d.patient_dispenses = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field user_dispenses", value)
		} else if value.Valid {
			d.user_dispenses = new(int)
			*d.user_dispenses = int(value.Int64)
		}
	}
	return nil
}

// QueryDrug queries the drug edge of the Dispense.
func (d *Dispense) QueryDrug() *DrugQuery {
	return (&DispenseClient{config: d.config}).QueryDrug(d)
}

// QueryPatient queries the patient edge of the Dispense.
func (d *Dispense) QueryPatient() *PatientQuery {
	return (&DispenseClient{config: d.config}).QueryPatient(d)
}

// QueryUser queries the user edge of the Dispense.
func (d *Dispense) QueryUser() *UserQuery {
	return (&DispenseClient{config: d.config}).QueryUser(d)
}

// Update returns a builder for updating this Dispense.
// Note that, you need to call Dispense.Unwrap() before calling this method, if this Dispense
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dispense) Update() *DispenseUpdateOne {
	return (&DispenseClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Dispense) Unwrap() *Dispense {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dispense is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dispense) String() string {
	var builder strings.Builder
	builder.WriteString("Dispense(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", note=")
	builder.WriteString(d.Note)
	builder.WriteByte(')')
	return builder.String()
}

// Dispenses is a parsable slice of Dispense.
type Dispenses []*Dispense

func (d Dispenses) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
