// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/wipha26/app/ent/dispense"
	"github.com/wipha26/app/ent/drug"
)

// DrugCreate is the builder for creating a Drug entity.
type DrugCreate struct {
	config
	mutation *DrugMutation
	hooks    []Hook
}

// SetName sets the name field.
func (dc *DrugCreate) SetName(s string) *DrugCreate {
	dc.mutation.SetName(s)
	return dc
}

// AddDispenseIDs adds the dispenses edge to Dispense by ids.
func (dc *DrugCreate) AddDispenseIDs(ids ...int) *DrugCreate {
	dc.mutation.AddDispenseIDs(ids...)
	return dc
}

// AddDispenses adds the dispenses edges to Dispense.
func (dc *DrugCreate) AddDispenses(d ...*Dispense) *DrugCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dc.AddDispenseIDs(ids...)
}

// Mutation returns the DrugMutation object of the builder.
func (dc *DrugCreate) Mutation() *DrugMutation {
	return dc.mutation
}

// Save creates the Drug in the database.
func (dc *DrugCreate) Save(ctx context.Context) (*Drug, error) {
	if _, ok := dc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := dc.mutation.Name(); ok {
		if err := drug.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	var (
		err  error
		node *Drug
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DrugMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DrugCreate) SaveX(ctx context.Context) *Drug {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DrugCreate) sqlSave(ctx context.Context) (*Drug, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DrugCreate) createSpec() (*Drug, *sqlgraph.CreateSpec) {
	var (
		d     = &Drug{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: drug.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: drug.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: drug.FieldName,
		})
		d.Name = value
	}
	if nodes := dc.mutation.DispensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.DispensesTable,
			Columns: []string{drug.DispensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dispense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
