// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/wipha26/app/ent/dispense"
	"github.com/wipha26/app/ent/patient"
)

// PatientCreate is the builder for creating a Patient entity.
type PatientCreate struct {
	config
	mutation *PatientMutation
	hooks    []Hook
}

// SetFirstname sets the firstname field.
func (pc *PatientCreate) SetFirstname(s string) *PatientCreate {
	pc.mutation.SetFirstname(s)
	return pc
}

// SetLastname sets the lastname field.
func (pc *PatientCreate) SetLastname(s string) *PatientCreate {
	pc.mutation.SetLastname(s)
	return pc
}

// SetCardid sets the cardid field.
func (pc *PatientCreate) SetCardid(s string) *PatientCreate {
	pc.mutation.SetCardid(s)
	return pc
}

// SetAllergic sets the allergic field.
func (pc *PatientCreate) SetAllergic(s string) *PatientCreate {
	pc.mutation.SetAllergic(s)
	return pc
}

// SetAge sets the age field.
func (pc *PatientCreate) SetAge(i int) *PatientCreate {
	pc.mutation.SetAge(i)
	return pc
}

// SetBrithday sets the brithday field.
func (pc *PatientCreate) SetBrithday(t time.Time) *PatientCreate {
	pc.mutation.SetBrithday(t)
	return pc
}

// SetNillableBrithday sets the brithday field if the given value is not nil.
func (pc *PatientCreate) SetNillableBrithday(t *time.Time) *PatientCreate {
	if t != nil {
		pc.SetBrithday(*t)
	}
	return pc
}

// AddDispenseIDs adds the dispenses edge to Dispense by ids.
func (pc *PatientCreate) AddDispenseIDs(ids ...int) *PatientCreate {
	pc.mutation.AddDispenseIDs(ids...)
	return pc
}

// AddDispenses adds the dispenses edges to Dispense.
func (pc *PatientCreate) AddDispenses(d ...*Dispense) *PatientCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pc.AddDispenseIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (pc *PatientCreate) Mutation() *PatientMutation {
	return pc.mutation
}

// Save creates the Patient in the database.
func (pc *PatientCreate) Save(ctx context.Context) (*Patient, error) {
	if _, ok := pc.mutation.Firstname(); !ok {
		return nil, &ValidationError{Name: "firstname", err: errors.New("ent: missing required field \"firstname\"")}
	}
	if v, ok := pc.mutation.Firstname(); ok {
		if err := patient.FirstnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "firstname", err: fmt.Errorf("ent: validator failed for field \"firstname\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Lastname(); !ok {
		return nil, &ValidationError{Name: "lastname", err: errors.New("ent: missing required field \"lastname\"")}
	}
	if v, ok := pc.mutation.Lastname(); ok {
		if err := patient.LastnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "lastname", err: fmt.Errorf("ent: validator failed for field \"lastname\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Cardid(); !ok {
		return nil, &ValidationError{Name: "cardid", err: errors.New("ent: missing required field \"cardid\"")}
	}
	if v, ok := pc.mutation.Cardid(); ok {
		if err := patient.CardidValidator(v); err != nil {
			return nil, &ValidationError{Name: "cardid", err: fmt.Errorf("ent: validator failed for field \"cardid\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Allergic(); !ok {
		return nil, &ValidationError{Name: "allergic", err: errors.New("ent: missing required field \"allergic\"")}
	}
	if v, ok := pc.mutation.Allergic(); ok {
		if err := patient.AllergicValidator(v); err != nil {
			return nil, &ValidationError{Name: "allergic", err: fmt.Errorf("ent: validator failed for field \"allergic\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Age(); !ok {
		return nil, &ValidationError{Name: "age", err: errors.New("ent: missing required field \"age\"")}
	}
	if v, ok := pc.mutation.Age(); ok {
		if err := patient.AgeValidator(v); err != nil {
			return nil, &ValidationError{Name: "age", err: fmt.Errorf("ent: validator failed for field \"age\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Brithday(); !ok {
		v := patient.DefaultBrithday()
		pc.mutation.SetBrithday(v)
	}
	var (
		err  error
		node *Patient
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PatientCreate) SaveX(ctx context.Context) *Patient {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PatientCreate) sqlSave(ctx context.Context) (*Patient, error) {
	pa, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pa.ID = int(id)
	return pa, nil
}

func (pc *PatientCreate) createSpec() (*Patient, *sqlgraph.CreateSpec) {
	var (
		pa    = &Patient{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: patient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Firstname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldFirstname,
		})
		pa.Firstname = value
	}
	if value, ok := pc.mutation.Lastname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldLastname,
		})
		pa.Lastname = value
	}
	if value, ok := pc.mutation.Cardid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldCardid,
		})
		pa.Cardid = value
	}
	if value, ok := pc.mutation.Allergic(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldAllergic,
		})
		pa.Allergic = value
	}
	if value, ok := pc.mutation.Age(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
		pa.Age = value
	}
	if value, ok := pc.mutation.Brithday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: patient.FieldBrithday,
		})
		pa.Brithday = value
	}
	if nodes := pc.mutation.DispensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.DispensesTable,
			Columns: []string{patient.DispensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dispense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pa, _spec
}
