// Code generated by entc, DO NOT EDIT.

package drug

const (
	// Label holds the string label denoting the drug type in the database.
	Label = "drug"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeDispenses holds the string denoting the dispenses edge name in mutations.
	EdgeDispenses = "dispenses"

	// Table holds the table name of the drug in the database.
	Table = "drugs"
	// DispensesTable is the table the holds the dispenses relation/edge.
	DispensesTable = "dispenses"
	// DispensesInverseTable is the table name for the Dispense entity.
	// It exists in this package in order to avoid circular dependency with the "dispense" package.
	DispensesInverseTable = "dispenses"
	// DispensesColumn is the table column denoting the dispenses relation/edge.
	DispensesColumn = "drug_dispenses"
)

// Columns holds all SQL columns for drug fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
