/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDispenseEdges,
    EntDispenseEdgesFromJSON,
    EntDispenseEdgesFromJSONTyped,
    EntDispenseEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDispense
 */
export interface EntDispense {
    /**
     * 
     * @type {EntDispenseEdges}
     * @memberof EntDispense
     */
    edges?: EntDispenseEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDispense
     */
    id?: number;
    /**
     * Note holds the value of the "note" field.
     * @type {string}
     * @memberof EntDispense
     */
    note?: string;
}

export function EntDispenseFromJSON(json: any): EntDispense {
    return EntDispenseFromJSONTyped(json, false);
}

export function EntDispenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDispense {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntDispenseEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function EntDispenseToJSON(value?: EntDispense | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntDispenseEdgesToJSON(value.edges),
        'id': value.id,
        'note': value.note,
    };
}


