/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrug,
    EntDrugFromJSON,
    EntDrugFromJSONTyped,
    EntDrugToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDispenseEdges
 */
export interface EntDispenseEdges {
    /**
     * 
     * @type {EntDrug}
     * @memberof EntDispenseEdges
     */
    drug?: EntDrug;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntDispenseEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntUser}
     * @memberof EntDispenseEdges
     */
    user?: EntUser;
}

export function EntDispenseEdgesFromJSON(json: any): EntDispenseEdges {
    return EntDispenseEdgesFromJSONTyped(json, false);
}

export function EntDispenseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDispenseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drug': !exists(json, 'drug') ? undefined : EntDrugFromJSON(json['drug']),
        'patient': !exists(json, 'patient') ? undefined : EntPatientFromJSON(json['patient']),
        'user': !exists(json, 'user') ? undefined : EntUserFromJSON(json['user']),
    };
}

export function EntDispenseEdgesToJSON(value?: EntDispenseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drug': EntDrugToJSON(value.drug),
        'patient': EntPatientToJSON(value.patient),
        'user': EntUserToJSON(value.user),
    };
}


