/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReactNode } from 'react';
import { exists, mapValues } from '../runtime';
import {
    EntPatientEdges,
    EntPatientEdgesFromJSON,
    EntPatientEdgesFromJSONTyped,
    EntPatientEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatient
 */
export interface EntPatient {
    [x: string]: ReactNode;
    /**
     * Age holds the value of the "age" field.
     * @type {number}
     * @memberof EntPatient
     */
    age?: number;
    /**
     * Allergic holds the value of the "allergic" field.
     * @type {string}
     * @memberof EntPatient
     */
    allergic?: string;
    /**
     * Brithday holds the value of the "brithday" field.
     * @type {string}
     * @memberof EntPatient
     */
    brithday?: string;
    /**
     * Cardid holds the value of the "cardid" field.
     * @type {string}
     * @memberof EntPatient
     */
    cardid?: string;
    /**
     * 
     * @type {EntPatientEdges}
     * @memberof EntPatient
     */
    edges?: EntPatientEdges;
    /**
     * Firstname holds the value of the "firstname" field.
     * @type {string}
     * @memberof EntPatient
     */
    firstname?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatient
     */
    id?: number;
    /**
     * Lastname holds the value of the "lastname" field.
     * @type {string}
     * @memberof EntPatient
     */
    lastname?: string;
}

export function EntPatientFromJSON(json: any): EntPatient {
    return EntPatientFromJSONTyped(json, false);
}

export function EntPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'age': !exists(json, 'age') ? undefined : json['age'],
        'allergic': !exists(json, 'allergic') ? undefined : json['allergic'],
        'brithday': !exists(json, 'brithday') ? undefined : json['brithday'],
        'cardid': !exists(json, 'cardid') ? undefined : json['cardid'],
        'edges': !exists(json, 'edges') ? undefined : EntPatientEdgesFromJSON(json['edges']),
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
    };
}

export function EntPatientToJSON(value?: EntPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'age': value.age,
        'allergic': value.allergic,
        'brithday': value.brithday,
        'cardid': value.cardid,
        'edges': EntPatientEdgesToJSON(value.edges),
        'firstname': value.firstname,
        'id': value.id,
        'lastname': value.lastname,
    };
}


